#![allow(dead_code)]
#![allow(nonstandard_style)]

/* automatically generated by rust-bindgen 0.69.4 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ARect {
    pub left: i32,
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
}
pub type ARect_value_type = i32;
#[repr(C)]
#[derive(Debug)]
pub struct native_handle {
    pub version: std::ffi::c_int,
    pub numFds: std::ffi::c_int,
    pub numInts: std::ffi::c_int,
    pub data: __IncompleteArrayField<std::ffi::c_int>,
}
pub type native_handle_t = native_handle;
pub type buffer_handle_t = *const native_handle_t;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum AIMapper_Version {
    AIMAPPER_VERSION_5 = 5,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum AIMapper_Error {
    AIMAPPER_ERROR_NONE = 0,
    AIMAPPER_ERROR_BAD_DESCRIPTOR = 1,
    AIMAPPER_ERROR_BAD_BUFFER = 2,
    AIMAPPER_ERROR_BAD_VALUE = 3,
    AIMAPPER_ERROR_NO_RESOURCES = 5,
    AIMAPPER_ERROR_UNSUPPORTED = 7,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AIMapper_MetadataType {
    pub name: *const std::ffi::c_char,
    pub value: i64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AIMapper_MetadataTypeDescription {
    pub metadataType: AIMapper_MetadataType,
    pub description: *const std::ffi::c_char,
    pub isGettable: bool,
    pub isSettable: bool,
    pub reserved: [u8; 32usize],
}
pub type AIMapper_DumpBufferCallback = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut std::ffi::c_void,
        metadataType: AIMapper_MetadataType,
        value: *const std::ffi::c_void,
        valueSize: usize,
    ),
>;
pub type AIMapper_BeginDumpBufferCallback =
    ::std::option::Option<unsafe extern "C" fn(context: *mut std::ffi::c_void)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AIMapperV5 {
    pub importBuffer: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *const native_handle_t,
            outBufferHandle: *mut buffer_handle_t,
        ) -> AIMapper_Error,
    >,
    pub freeBuffer:
        ::std::option::Option<unsafe extern "C" fn(buffer: buffer_handle_t) -> AIMapper_Error>,
    pub getTransportSize: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            outNumFds: *mut u32,
            outNumInts: *mut u32,
        ) -> AIMapper_Error,
    >,
    pub lock: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            cpuUsage: u64,
            accessRegion: ARect,
            acquireFence: std::ffi::c_int,
            outData: *mut *mut std::ffi::c_void,
        ) -> AIMapper_Error,
    >,
    pub unlock: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            releaseFence: *mut std::ffi::c_int,
        ) -> AIMapper_Error,
    >,
    pub flushLockedBuffer:
        ::std::option::Option<unsafe extern "C" fn(buffer: buffer_handle_t) -> AIMapper_Error>,
    pub rereadLockedBuffer:
        ::std::option::Option<unsafe extern "C" fn(buffer: buffer_handle_t) -> AIMapper_Error>,
    pub getMetadata: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            metadataType: AIMapper_MetadataType,
            destBuffer: *mut std::ffi::c_void,
            destBufferSize: usize,
        ) -> i32,
    >,
    pub getStandardMetadata: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            standardMetadataType: i64,
            destBuffer: *mut std::ffi::c_void,
            destBufferSize: usize,
        ) -> i32,
    >,
    pub setMetadata: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            metadataType: AIMapper_MetadataType,
            metadata: *const std::ffi::c_void,
            metadataSize: usize,
        ) -> AIMapper_Error,
    >,
    pub setStandardMetadata: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            standardMetadataType: i64,
            metadata: *const std::ffi::c_void,
            metadataSize: usize,
        ) -> AIMapper_Error,
    >,
    pub listSupportedMetadataTypes: ::std::option::Option<
        unsafe extern "C" fn(
            outDescriptionList: *mut *const AIMapper_MetadataTypeDescription,
            outNumberOfDescriptions: *mut usize,
        ) -> AIMapper_Error,
    >,
    pub dumpBuffer: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            dumpBufferCallback: AIMapper_DumpBufferCallback,
            context: *mut std::ffi::c_void,
        ) -> AIMapper_Error,
    >,
    pub dumpAllBuffers: ::std::option::Option<
        unsafe extern "C" fn(
            beginDumpCallback: AIMapper_BeginDumpBufferCallback,
            dumpBufferCallback: AIMapper_DumpBufferCallback,
            context: *mut std::ffi::c_void,
        ) -> AIMapper_Error,
    >,
    pub getReservedRegion: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: buffer_handle_t,
            outReservedRegion: *mut *mut std::ffi::c_void,
            outReservedSize: *mut u64,
        ) -> AIMapper_Error,
    >,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct AIMapper {
    pub version: AIMapper_Version,
    pub v5: AIMapperV5,
}
